### ISSUE TITLE
bug for remove(0)?

### ISSUE THREAD

**Issue by mbehr1** [eglimi/cpptime#1]
I think there is a bug: 
remove(0) (if no timer is active/ever used) will pass the

if(events.size()< id) {
			return false;
}
check (events.size()==0 not < 0)
but in the end there is no item. So the check should be extended to e.g.
if (events.size()>0 && events.size()<id)
or id being started with 1 for the first item?

**Comment by eglimi** [comment]
This is true, well spotted. Thank you very much for opening an issue for this! Would you like to create a pull request for this?

**Comment by mbehr1** [comment]
will do.

**Comment by mbehr1** [comment]
see PR #2 . all tests pass.

**Comment by eglimi** [comment]
That was quick! Thanks again.

**Comment by mbehr1** [comment]
Welcome!
